updates CI

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,7 +7,6 @@ on:
   push:
     branches:
       - 'master'
-  
 
 jobs:
   build:
@@ -15,7 +14,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: [3.7, 3.8]
+        python-version: [3.6, 3.7, 3.8]
 
     steps:
     - uses: actions/checkout@v2
@@ -26,17 +25,8 @@ jobs:
 
     - name: Install dependencies
       run: |
-        python -m pip install --upgrade pip
-        pip install flake8
-        if [ -f requirements/requirements.txt ]; \
-        then pip install -r requirements/requirements.txt; fi
-
-    - name: Lint with flake8
-      run: |
-        # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+        python -m pip install --upgrade pip setuptools wheel
+        if [ -f requirements/test.txt ]; then pip install -r requirements/test.txt; fi
     
     - name: Start mongoDB
       run: |
@@ -68,15 +58,15 @@ jobs:
     #     echo extracted issue: ${GITHUB_HEAD_REF} | egrep -o 'GA-[0-9]{1,4}'
 
 
-    - name: Generate test report
-      run: |
-        pytest --cov-report=xml
+    # - name: Generate test report
+    #   run: |
+    #     pytest --cov-report=xml
 
-    - name: Upload coverage to Codecov
-      uses: codecov/codecov-action@v1
-      with:
-        token: ${{ secrets.CODECOV_TOKEN }}
+    # - name: Upload coverage to Codecov
+    #   uses: codecov/codecov-action@v1
+    #   with:
+    #     token: ${{ secrets.CODECOV_TOKEN }}
 
-    - name: Check Coverage
-      run: |
-        coverage report --fail-under=40 --omit '.venv/*' || (echo 'Insufficient coverage' && $(exit 1))
+    # - name: Check Coverage
+    #   run: |
+    #     coverage report --fail-under=40 --omit '.venv/*' || (echo 'Insufficient coverage' && $(exit 1))
